### ISSUE TITLE
Connect with service principal

### ISSUE THREAD

**Issue by matejskubic** [microsoft/PowerPlatformConnectors#708]
**Is your feature request related to a problem? Please describe.**
Custom connector should provide an option to connect with service principal credentials.

**Describe the solution you'd like**
Like other standard connectors provides option to connect with service principal credentials.
![image](https://user-images.githubusercontent.com/839965/109682755-0206df80-7b7f-11eb-8fce-2037188972cd.png)
![image](https://user-images.githubusercontent.com/839965/109682884-1945cd00-7b7f-11eb-9e49-ed6a75b1d6c6.png)

**Describe alternatives you've considered**
Already tried in swagger editor to change `flow` from `accessCode` to `application`. After *Update connector* action oauth2 flow is changed back to *accessCode*.

Sample yaml:
```yaml
securityDefinitions:
  oauth2_auth:
    type: oauth2
    flow: application 
    tokenUrl: https://login.microsoftonline.com/common/oauth2/token

```

**Additional context**
Custom connector should provide connectivity without user context (aka service-to-service communication) and application permission (not delegated).
